// Generated by CoffeeScript 1.3.3
(function() {
  var app, express, http, path, routes, server, user;

  express = require('express');

  routes = require('./routes');

  user = require('./routes/user');

  http = require('http');

  path = require('path');

  app = express();

  app.configure(function() {
    app.set('port', process.env.PORT || 3000);
    app.set('views', __dirname + '/views');
    app.set('view engine', 'ejs');
    app.use(express.favicon());
    app.use(express.logger('dev'));
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(app.router);
    app.use(require('less-middleware')({
      src: __dirname + '/public'
    }));
    app.use(express["static"](path.join(__dirname, 'public')));
  });

  app.configure('development', function() {
    return app.use(express.errorHandler());
  });

  app.get('/', routes.index);

  server = http.createServer(app);

  server.listen(app.get('port'), function() {
    return console.log('Express start on port ' + app.get('port'));
  });

}).call(this);
